FROM centos:7.6.1810

ARG gcc_version=10.2-2020.11
ENV GCC_VERSION $gcc_version
ENV SOURCE_DIR /root/source

# Install requirements
RUN yum install -y wget tar git make redhat-lsb-core autoconf automake libtool glibc-devel libaio-devel openssl-devel apr-devel lksctp-tools unzip zip libaio libaio-dev

# Install Java
RUN yum install -y java-1.8.0-openjdk-devel

RUN mkdir $SOURCE_DIR
WORKDIR $SOURCE_DIR

# Install aarch64 gcc 10.2 toolchain
RUN wget https://developer.arm.com/-/media/Files/downloads/gnu-a/$GCC_VERSION/binrel/gcc-arm-$GCC_VERSION-x86_64-aarch64-none-linux-gnu.tar.xz && \
   tar xvf gcc-arm-$GCC_VERSION-x86_64-aarch64-none-linux-gnu.tar.xz && mv gcc-arm-$GCC_VERSION-x86_64-aarch64-none-linux-gnu /opt/
ENV PATH="/opt/gcc-arm-$GCC_VERSION-x86_64-aarch64-none-linux-gnu/bin:${PATH}"

RUN wget --no-check-certificate https://mirror.archlinuxarm.org/aarch64/core/libaio-0.3.113-2-aarch64.pkg.tar.xz && \
    mkdir /aarch-libaio && mv libaio-0.3.113-2-aarch64.pkg.tar.xz /aarch-libaio/ && cd /aarch-libaio && \
    tar -xf libaio-0.3.113-2-aarch64.pkg.tar.xz && \
    ln -s /aarch-libaio/usr/lib/libaio.so /opt/gcc-arm-${GCC_VERSION}-x86_64-aarch64-none-linux-gnu/aarch64-none-linux-gnu/lib64 && \
    ln -s /aarch-libaio/usr/include/libaio.h /opt/gcc-arm-${GCC_VERSION}-x86_64-aarch64-none-linux-gnu/aarch64-none-linux-gnu/include

ENV JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk/"

# Cleanup
RUN rm -rf $SOURCE_DIR
RUN yum clean all && \
    rm -rf /var/cache/yum